ni/accounts/urls.py
"""
URLConf for Django user registration.

Recommended usage is to use a call to ``include()`` in your project's
root URLConf to include this URLConf for any URL beginning with
'/accounts/'.

"""
from django.conf.urls import patterns

from ni.accounts.views import RegistrationComplete
# extending the urls in contacts
# from satchmo_store.contact.urls import urlpatterns
from satchmo_utils.signals import collect_urls
from ni import accounts
# The following import of satchmo_store.contact.config should not be removed
# because it is sometimes indirectly important for loading
# config_value('SHOP', 'ACCOUNT_VERIFICATION')

# pylint: disable=unused-import
import satchmo_store.contact.config

# Activation keys get matched by \w+ instead of the more specific
# [a-fA-F0-9]+ because a bad activation key should still get to the view;
# that way it can return a sensible "invalid key" message instead of a
# confusing 404.

# pylint: disable=invalid-name
urlpatterns = patterns(
    'ni.accounts.views',

    (r'^activate/(?P<activation_key>\w+)/$', 'activate', {},
     'registration_activate'),

    (r'^login/$', 'emaillogin', {'template_name': 'registration/login.html'},
     'auth_login'),

    (r'^register/$', 'register', {}, 'registration_register'),

    (r'^secure/login/$', 'emaillogin',
     {'SSL': True, 'template_name': 'registration/login.html'},
     'auth_secure_login'),
)

urlpatterns += patterns(
    '',

    ('^logout/$', 'django.contrib.auth.views.logout',
     {'template_name': 'registration/logout.html'}, 'auth_logout'),
)

urlpatterns += patterns(
    '',
    (r'^register/complete/$',
     RegistrationComplete.as_view(
         template_name='registration/registration_complete.html'), {},
     'registration_complete'),
)

# Dictionary for authentication views
password_reset_dict = {
    'template_name': 'registration/password_reset_form.html',
    'email_template_name': 'registration/password_reset.txt',
}

# the "from email" in password reset is problematic... it is hard coded as None
urlpatterns += patterns(
    'django.contrib.auth.views',

    (r'^password_reset/$', 'password_reset', password_reset_dict,
     'auth_password_reset'),

    (r'^password_reset/done/$', 'password_reset_done',
     {'template_name': 'registration/password_reset_done.html'},
     'password_reset_done'),

    (r'^password_change/$', 'password_change',
     {'template_name': 'registration/password_change_form.html'},
     'auth_password_change'),

    (r'^password_change/done/$', 'password_change_done',
     {'template_name': 'registration/password_change_done.html'},
     'password_change_done'),

    (r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
     'password_reset_confirm'),

    (r'^reset/done/$', 'password_reset_complete'),
)

collect_urls.send(sender=accounts, patterns=urlpatterns)

ni/urls.py
"""
Custom urls for ni
"""

from django.conf.urls import patterns, include, url

from satchmo_store.urls import urlpatterns
from ni import views

# pylint: disable=invalid-name
urlpatterns = patterns(
    '',
    url(r'^ping', views.ping, name='health'),

    url(r'^accounts/', include('ni.accounts.urls')),

    url(r'^create/', views.create.create_view),

    url(r'^search/', views.search.search_view, name='ni-search')

    # url(r'^search/', include('haystack.urls')),

) + urlpatterns

# staticfiles testing
from django.conf import settings

urlpatterns += patterns(
    '',
    url(r'^favicon\.ico$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT,
        'path': 'favicon/favicon.ico'
    })
)
# if settings.DEBUG:
# import debug_toolbar
#
# # Server statics and uploaded media
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += [
#     url(r'^__debug__/', include(debug_toolbar.urls)),
# ]

satchmo/satchmo_store/shop/urls.py
from django.conf.urls import patterns, include
from django.views.generic.base import TemplateView
from product.urls import urlpatterns as productpatterns
from satchmo_store import shop
from satchmo_store.shop.views.sitemaps import sitemaps
from satchmo_utils.signals import collect_urls

urlpatterns = shop.get_satchmo_setting('SHOP_URLS')

urlpatterns += patterns('satchmo_store.shop.views',
    (r'^$','home.home', {}, 'satchmo_shop_home'),
    (r'^add/$', 'smart.smart_add', {}, 'satchmo_smart_add'),
    (r'^cart/$', 'cart.display', {}, 'satchmo_cart'),
    (r'^cart/accept/$', 'cart.agree_terms', {}, 'satchmo_cart_accept_terms'),
    (r'^cart/add/$', 'cart.add', {}, 'satchmo_cart_add'),
    (r'^cart/add/ajax/$', 'cart.add_ajax', {}, 'satchmo_cart_add_ajax'),
    (r'^cart/qty/$', 'cart.set_quantity', {}, 'satchmo_cart_set_qty'),
    (r'^cart/qty/ajax/$', 'cart.set_quantity_ajax', {}, 'satchmo_cart_set_qty_ajax'),
    (r'^cart/remove/$', 'cart.remove', {}, 'satchmo_cart_remove'),
    (r'^cart/remove/ajax/$', 'cart.remove_ajax', {}, 'satchmo_cart_remove_ajax'),
    (r'^checkout/', include('payment.urls')),
    (r'^contact/$', 'contact.form', {}, 'satchmo_contact'),
    (r'^history/$', 'orders.order_history', {}, 'satchmo_order_history'),
    (r'^quickorder/$', 'cart.add_multiple', {}, 'satchmo_quick_order'),
    (r'^tracking/(?P<order_id>\d+)/$', 'orders.order_tracking', {}, 'satchmo_order_tracking'),
    (r'^search/$', 'search.search_view', {}, 'satchmo_search'),
)

# here we add product patterns directly into the root url
urlpatterns += productpatterns

urlpatterns += patterns('',
    (r'^contact/thankyou/$',
        TemplateView.as_view(template_name='shop/contact_thanks.html'), {},
        'satchmo_contact_thanks'),
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': sitemaps},
        'satchmo_sitemap_xml'),

)

# here we are sending a signal to add patterns to the base of the shop.
collect_urls.send(sender=shop, patterns=urlpatterns)

satchmo/satchmo_store/shop/models.py
"""
Configuration items for the shop.
Also contains shopping cart and related classes.
"""

from decimal import Decimal, ROUND_CEILING
from django.contrib.sites.models import Site
from django.conf import settings
from django.core import urlresolvers
from django.db import models
from django.utils.encoding import force_unicode
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext, ugettext_lazy as _
from django.utils import timezone
from l10n.models import Country
from l10n.utils import moneyfmt
from livesettings import ConfigurationSettings, config_value
from product.models import Discount, Product, Price, get_product_quantity_adjustments
from product.prices import PriceAdjustmentCalc, PriceAdjustment
from satchmo_store.contact.models import Contact
from satchmo_utils.fields import CurrencyField
from satchmo_utils.numbers import trunc_decimal
import shipping.fields
import payment.config
from satchmo_utils.iterchoices import iterchoices_db
from tax.utils import get_tax_processor
import keyedcache
import logging
import operator
import signals

log = logging.getLogger('satchmo_store.shop.models')

class NullConfig(object):
    """Standin for a real config when we don't have one yet."""

    def __init__(self):
        self.store_name = self.store_description = _("Test Store")
        self.store_email = self.street1 = self.street2 = self.city = self.state = self.postal_code = self.phone = ""
        self.site = self.country = None
        self.in_country_only = True
        self.sales_country = None

    def _options(self):
        return ConfigurationSettings()

    options = property(fget=_options)

    def __str__(self):
        return "Test Store - no configured store exists!"

class ConfigManager(models.Manager):
    def get_current(self, site=None):
        """Convenience method to get the current shop config"""
        if not site:
            site = Site.objects.get_current()

        site = site.id

        try:
            shop_config = keyedcache.cache_get("Config", site)
        except keyedcache.NotCachedError, nce:
            try:
                shop_config = self.get(site__id__exact=site)
                keyedcache.cache_set(nce.key, value=shop_config)
            except Config.DoesNotExist:
                log.warning("No Shop Config found, using test shop config for site=%s.", site)
                shop_config = NullConfig()

        return shop_config

class Config(models.Model):
    """
    Used to store specific information about a store.  Also used to
    configure various store behaviors
    """
    site = models.OneToOneField(Site, verbose_name=_("Site"), primary_key=True)
    store_name = models.CharField(_("Store Name"),max_length=100, unique=True)
    store_description = models.TextField(_("Description"), blank=True, null=True)
    store_email = models.EmailField(_("Email"), blank=True, null=True, max_length=75)
    street1=models.CharField(_("Street"),max_length=50, blank=True, null=True)
    street2=models.CharField(_("Street"), max_length=50, blank=True, null=True)
    city=models.CharField(_("City"), max_length=50, blank=True, null=True)
    state=models.CharField(_("State"), max_length=30, blank=True, null=True)
    postal_code=models.CharField(_("Zip Code"), blank=True, null=True, max_length=9)
    country=models.ForeignKey(Country, blank=False, null=False, verbose_name=_('Country'))
    phone = models.CharField(_("Phone Number"), blank=True, null=True, max_length=30)
    in_country_only = models.BooleanField(
        _("Only sell to in-country customers?"),
        default=True)
    sales_country = models.ForeignKey(
        Country, blank=True, null=True,
        related_name='sales_country',
        verbose_name=_("Default country for customers"))
    shipping_countries = models.ManyToManyField(
        Country,
        blank=True,
        verbose_name=_("Shipping Countries"),
        related_name="shop_configs")

    objects = ConfigManager()

    def _options(self):
        return ConfigurationSettings()

    options = property(fget=_options)

    def areas(self):
        """Get country areas (states/counties).  Used in forms."""
        if self.in_country_only:
            return self.sales_country.adminarea_set.filter(active=True)
        else:
            return None

    def countries(self):
        """Get country selections.  Used in forms."""
        if self.in_country_only:
            return Country.objects.filter(pk=self.sales_country.pk)
        else:
            return self.shipping_countries.filter(active=True)


    def _base_url(self, secure=False):
        prefix = "http"
        if secure:
            prefix += "s"
        return prefix + "://" + self.site.domain

    base_url = property(fget=_base_url)

    def save(self, **kwargs):
        keyedcache.cache_delete("Config", self.site.id)
        # ensure the default country is in shipping countries
        mycountry = self.country

        if mycountry:
            if not self.sales_country:
                log.debug("%s: No sales_country set, adding country of store, '%s'", self, mycountry)
                self.sales_country = mycountry

# This code doesn't work when creating a new site. At the time of creation, all of the necessary relationships
# aren't setup. I modified the load_store code so that it would create this relationship manually when running
# with sample data. This is a bit of a django limitation so I'm leaving this in here for now. - CBM
#            salescountry = self.sales_country
#            try:
#                need = self.shipping_countries.get(pk=salescountry.pk)
#            except Country.DoesNotExist:
#                log.debug("%s: Adding default country '%s' to shipping countries", self, salescountry.iso2_code)
#                self.shipping_countries.add(salescountry)
        else:
            log.warn("%s: has no country set", self)

        super(Config, self).save(**kwargs)
        keyedcache.cache_set("Config", self.site.id, value=self)

    def __unicode__(self):
        return self.store_name

    class Meta:
        verbose_name = _("Store Configuration")
        verbose_name_plural = _("Store Configurations")


class NullCart(object):
    """Standin for a real cart when we don't have one yet.  More convenient than testing for null all the time."""
    desc = None
    date_time_created = None
    customer = None
    total = Decimal("0")
    numItems = 0

    def add_item(self, *args, **kwargs):
        pass

    def remove_item(self, *args, **kwargs):
        pass

    def empty(self):
        pass

    def __str__(self):
        return "NullCart (empty)"

    def __iter__(self):
        return iter([])

    def __len__(self):
        return 0

    def save(self):
        pass

class OrderCart(NullCart):
    """Allows us to fake a cart if we are reloading an order."""

    def __init__(self, order):
        self._order = order

    def _numItems(self):
        return self._order.orderitem_set.count()

    numItems = property(_numItems)

    def _cartitem_set(self):
        return self._order.orderitem_set

    cartitem_set = property(_cartitem_set)

    def _total(self):
        return self._order.balance

    total = property(_total)

    is_shippable = False

    def __str__(self):
        return "OrderCart (%i) = %i" % (self._order.id, len(self))

    def __len__(self):
        return self.numItems

    def __iter__(self):
        return iter(self.cartitem_set.all())

class CartManager(models.Manager):

    def from_request(self, request, create=False, return_nullcart=True):
        """Get the current cart from the request"""
        cart = None
        try:
            contact = Contact.objects.from_request(request, create=False)
        except Contact.DoesNotExist:
            contact = None

        if 'cart' in request.session:
            cartid = request.session['cart']
            if cartid == "order":
                log.debug("Getting Order Cart from request")
                try:
                    order = Order.objects.from_request(request)
                    cart = OrderCart(order)
                except Order.DoesNotExist:
                    pass

            else:
                try:
                    cart = Cart.objects.get(id=cartid)
                except Cart.DoesNotExist:
                    log.debug('Removing invalid cart from session')
                    del request.session['cart']

        if isinstance(cart, NullCart) and not isinstance(cart, OrderCart) and contact is not None:
            carts = Cart.objects.filter(customer=contact)
            if carts.count() > 0:
                cart = carts[0]
                request.session['cart'] = cart.id

        if not cart:
            if create:
                site = Site.objects.get_current()
                if contact is None:
                    cart = Cart(site=site)
                else:
                    cart = Cart(site=site, customer=contact)
                cart.save()
                request.session['cart'] = cart.id

            elif return_nullcart:
                cart = NullCart()

            else:
                raise Cart.DoesNotExist()

        #log.debug("Cart: %s", cart)
        return cart


class Cart(models.Model):
    """
    Store items currently in a cart
    The desc isn't used but it is needed to make the admin interface work appropriately
    Could be used for debugging
    """
    site = models.ForeignKey(Site, verbose_name=_('Site'))
    desc = models.CharField(_("Description"), blank=True, null=True, max_length=10)
    date_time_created = models.DateTimeField(_("Creation Date"))
    customer = models.ForeignKey(Contact, blank=True, null=True, verbose_name=_('Customer'))

    objects = CartManager()

    def _get_count(self):
        itemCount = 0
        for item in self.cartitem_set.all():
            itemCount += item.quantity
        return (itemCount)
    numItems = property(_get_count)

ni/views/create.py
from django.http import HttpResponseRedirect
from django.template import RequestContext

from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
from django.contrib.sites.models import Site

from ni.forms import ShopForm
from ni.models import Shop

import logging

log = logging.getLogger('ni.views.create')


@login_required
def create_view(request, redirect=None, template="shop/create/new.html"):
    """
    Handle all shop creation logic.
    """

    form = ShopForm(request.POST)
    if request.method == 'POST' and form.is_valid():
            new_shop = Shop(
                name=form.cleaned_data['name'],
                owner=request.user,
                site=Site.objects.get_current()
                )
            new_shop.save()

            # look for explicit "next"
            next = request.POST.get('next', None)
            if not next:
                if redirect:
                    next = redirect
                else:
                    next = '/'
            return HttpResponseRedirect(next)

    form = ShopForm()
    context = RequestContext(request, {'form': form})

    return render_to_response(template, context_instance=context)

ni/views/ping.py
import json

from django.http import HttpResponse


def ping(request):
    response_data = {}
    response_data['result'] = 'in the pushup position'
    response_data['message'] = 'dogs are always'
    return HttpResponse(json.dumps(response_data),
                        content_type="application/json")

satchmo/satchmo_store/shop/views/common.py
"""Common shop views"""

ni/templates/shop/checkout/authentication_required.html
{% extends "shop/base.html" %} {% load url from future %}
{% load i18n %} 
 
{% block navbar %} 
    <li class="first"><a href="{{ shop_base }}/">{% trans "Home" %}</a></li> 
    <li>{% trans "Checkout" %}</li> 
{% endblock %} 
 
{% block content %} 
    <h3>{% trans "Authentication required" %}</h3> 
    <div id="checkoutprogress"> 
        <ul> 
            <li class="first">{% trans "Ship/Bill" %}</li> 
            <li>{% trans "Payment" %}</li> 
            <li>{% trans "Confirmation" %}</li> 
        </ul> 
    </div> 
    <form method="post" action="{% if is_secure %}{% url 'auth_secure_login' %}{% else %}{{ login_url }}{% endif %}">{% csrf_token %} 
        <input type="hidden" name="next" value="{% url 'satchmo_checkout-step1' %}" /> 
        <table> 
            <tr> 
                <td colspan="2"> 
                    {% trans "In order to have access to your products and order history, please log in. After that you may continue to checkout with your current cart." %}
                </td> 
            </tr> 
            <tr><td><label for="id_username">{% trans "Username or email" %}:</label></td><td><input type="text" id="id_username" class="vTextField required" name="username" size="15" value="" maxlength="75" /></td></tr>
            <tr><td><label for="id_password">{% trans "Password" %}:</label></td><td><input type="password" id="id_password" class="vPasswordField required" name="password" size="15" value="" maxlength="30" /></td></tr> 
            <tr><td>&nbsp;</td><td><input type="submit" value="{% trans "Login" %}" /></td></tr> 
        </table> 
    </form> 
     
    <p>{% trans "If you do not have an account, please" %} <a href="{% url 'registration_register' %}?next={% url 'satchmo_checkout-step1' %}">{% trans "click here" %}</a>.</p> 
    <p>{% trans "If you do not remember your password, please" %} <a href="{% url 'auth_password_reset' %}">{% trans "click here</a> to have it reset." %}</p> 
{% endblock %} 

ni/templates/shop/checkout/balance_remaining.html
{% extends "shop/base.html" %}{% load url from future %}
{% load i18n %}
{% load satchmo_order satchmo_currency %}

{% block navbar %}
   <li class="first"><a href="{{ shop_base }}/">{% trans "Home" %}</a></li>
   <li>{% trans "Checkout" %}</li>
{% endblock %}

{% block content %}
    <div id="orderstatus">
    <h4>{% trans "Order Balance" %}</h4>
        <form method="post" action="{% url 'satchmo_balance_remaining' %}">{% csrf_token %}
            <table>
                <tr><td colspan="2">{% with order.balance|currency as orderbalance %}
                    {% blocktrans %}To complete this order, you need to pay the {{ orderbalance }} balance remaining on this order.{% endblocktrans %}
                    {% endwith %}
                </td></tr>
                <tr><td colspan="2">
                    {% ifequal paymentmethod_ct 1 %}{# If we only have one payment method, then the form renders it as a hidden field #}{{ form.paymentmethod }}
                    {% else %}<h4>{% trans "How do you want to pay?" %}</h4></td></tr>
                <tr><td><label for="id_paymentmethod">{% trans "Payment method" %}*</label></td> <td>{{ form.paymentmethod }}</td></tr>
                {% if form.paymentmethod.errors %}<tr><td>&nbsp;</td><td>*** {{ form.paymentmethod.errors|join:", " }}</td></tr>{% endif %}
                {% endifequal %}
                <tr><td></td><td><input type="submit" value="{% trans "Continue Checkout" %}"/></td></tr>
            </table>
        </form>
    </div>
{% endblock %}

ni/templates/shop/checkout/base_confirm.html
{% extends "shop/base.html" %}{% load url from future %}
{% load i18n %}
{% load satchmo_currency %}
{% load satchmo_order %}

{% block navbar %}
	<li class="first"><a href="{{ shop_base }}/">{% trans "Home" %}</a></li>
	<li>{% trans "Checkout" %}</li>
{% endblock %}

{% block content %}
	<h3>{% trans "Checkout" %}</h3>
	<div id="checkoutprogress">
		<ul>
		    <li class="first"><a href="{% url 'satchmo_checkout-step1' %}">{% trans "Ship/Bill" %}</a></li>
		    <li>{% block payment_step %}<a href="{{ checkout_step2 }}">{% trans "Payment" %}</a>{% endblock %}</li>
		    <li class="active">{% trans "Confirmation" %}</li>
		</ul>
	</div>
	{% block error_processing %}
	{% if errors %}
	    <h3>{% block errorheader %}{% trans "The following error was returned while trying to process your payment. Please correct and resubmit." %}{% endblock %}</h3>
	    {{ errors }}
	{% else %}
	    <h3>{% trans "Please validate the following information, then submit your order." %}</h3>
	{% endif %}
	{% endblock %}

	{% block order_details %}
	    {% order_details order default_view_tax %}
	{% endblock %}

	{% block payment_display %}
	{# override for module-specific needs, such as displaying card info #}
	{% endblock %}

	{% block payment_form %}
	{# override with any payment-module specific needs #}
	<form method="post" action=".">{% csrf_token %}
		<input type="hidden" name="Process" value="True">
		<input type="submit" value="{% trans "Purchase Items" %}"/>
	</form>
	{% endblock %}
{% endblock content %}

ni/templates/shop/checkout/base_pay_ship.html
{% extends "shop/base.html" %}{% load url from future %}
{% load i18n %}

{% block content %}
<div class="ship-form form-bg">
    <div class="form-container">
        <div id="checkoutprogress">
        <ul>
            <li class="first"><a href="{% url 'satchmo_checkout-step1' %}">{% trans "Ship/Bill" %}</a></li>
            <li class="active">{% trans "Payment" %}</li>
            <li>{% trans "Confirmation" %}</li>
        </ul>
        </div>

        {% if form.errors %}
            <h2>{% blocktrans count form.errors|length as count %}Please correct the following error:{% plural %}Please correct the following errors:{% endblocktrans %}</h2>
            {% if form.non_field_errors %}<p>
            {{ form.non_field_errors }}
            </p>{% endif %}
        {% endif %}

        <form method="post" action=".">{% csrf_token %}
        <table>

            {% block payment_table %}
            {# put your payment module specific rows here.  For example, CC number. #}
            {% endblock %}
            
            {% if cart.is_shippable %}
            
                    {% if form.shipping_hidden %}
                        {{ form.shipping }}
                        </table>
                    {% else %}
                    <tr><td><h4>{% trans "Shipping Information" %}</h4></td></tr>
                        </table>
                        {% block shipping_table %}
                        <div id="shipping">
                        {% if form.shipping_description or form.shipping.field.choices|length_is:1 %}
                        <label for="id_shipping">{% trans "The following shipping method will be used" %}:</label>
                        {% else %}
                        <label for="id_shipping">{% trans "Please choose your preferred shipping method" %}</label>
                        {% endif %}
                        {{ form.shipping }}
                        {% if form.shipping_description %}<br/>{{ form.shipping_description }}{% endif %}
                        {% if form.shipping.errors %}*** {{ form.shipping.errors|join:", " }}{% endif %}
                        </div>
                        {% endblock %}
                    {% endif %}

            {% else %}

                <tr><td colspan="2"><h4>{% trans "There are no items in this order to ship." %}</h4></td></tr>
                <tr><td colspan="2"> {{ form.shipping }} </td></tr>
            </table>

            {% endif %}
            
            {% if form.shipping.field.choices|length_is:0 and cart.is_shippable %}
                <h4>{% blocktrans %}No valid shipping method is available. Please verify that your address is correct.{% endblocktrans %}</h4>
            {% else %}
                <input type="submit" value="{% trans "Confirm" %}"/>
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}

ni/templates/shop/checkout/form.html
{% extends "shop/base.html" %}{% load url from future %}
{% load i18n %}

{% block extra-head %}
{% include "contact/_contact_info_form.html" %}
{% endblock %}

{% block content %}
<div class="ship-form form-bg">
    <div class="form-container">
        <div id="checkoutprogress">
        <ul>
            <li class="first active">{% trans "Ship/Bill" %}</li>
            <li>{% trans "Payment" %}</li>
            <li>{% trans "Confirmation" %}</li>
        </ul>
        </div>
        <h4>{% trans "Please complete the following information in order to submit your order." %}</h4>
        {% if form.non_field_errors %}
        <h2>{% trans "Please correct the following error:" %}</h2>
        {{ form.non_field_errors }}
        {% endif %}
        {% if user.is_anonymous %}
        Checkout out as: Guest
        Have an account? Login. 
        {% endif %}

        <form method="post" action="{% url 'satchmo_checkout-step1' %}">{% csrf_token %}
        <table>

            {% ifequal paymentmethod_ct 1 %}
                {# If we only have one payment method, then the form renders it as a hidden field #}{{ form.paymentmethod }}
            {% else %}
            <tr><td colspan="2"><h4>{% trans "How do you want to pay?" %}</h4></td></tr>
            <tr><td><label for="id_paymentmethod">{% trans "Payment method" %}*</label></td> <td><div id="payment">{{ form.paymentmethod }}</div></td></tr>
            {% if form.paymentmethod.errors %}<tr><td class="error" colspan="2">*** {{ form.paymentmethod.errors|join:", " }}</td></tr>{% endif %}
            {% endifequal %}

            <tr><td colspan="2"><h4>{% trans "Basic Information" %}</h4></td></tr>
            <tr><td><label for="id_email">{% trans "Email address" %}*</label></td> <td>{{ form.email }}</td></tr>
            {% if form.email.errors %}<tr><td class="error" colspan="2">*** {{ form.email.errors|join:", " }}</td></tr>{% endif %}

            <tr><td><label for="id_first_name">{% trans "First name" %}{% if form.first_name.field.required %}*{% endif %}</label></td><td> {{ form.first_name }}</td></tr>
           {% if form.first_name.errors %}<tr><td class="error" colspan="2">*** {{ form.first_name.errors|join:", " }}</td></tr>{% endif %}

            <tr><td><label for="id_last_name">{% trans "Last name" %}{% if form.last_name.field.required %}*{% endif %}</label></td><td> {{ form.last_name }}</td></tr>
            {% if form.last_name.errors %}<tr><td class="error" colspan="2">*** {{ form.last_name.errors|join:", " }}</td></tr>{% endif %}

            <tr><td><label for="id_phone">{% trans "Phone number" %}{% if form.phone.field.required %}*{% endif %}</label></td><td> {{ form.phone }}</td></tr>
            {% if form.phone.errors %}<tr><td class="error" colspan="2">*** {{ form.phone.errors|join:", " }}</td></tr>{% endif %}

            {% block billing-info %}{% include "contact/_contact_info_form_billing.html" %}{% endblock %}

        {% if cart.is_shippable %}
            {% block shipping-info %}{% include "contact/_contact_info_form_shipping.html" %}{% endblock %}
        {% endif %}

        {% if form.discount.is_hidden %}
            {{ form.discount }}
        {% else %}
            <tr><td colspan="2"><h4>{% trans "Discounts" %}</h4></td></tr>
            <tr><td><label for="id_discount">{% trans "Discount code" %}</label></td><td>{{ form.discount }}</td></tr>
            {% if form.discount.errors %}<tr><td class="error" colspan="2">*** {{ form.discount.errors|join:", " }}</td></tr>{% endif %}
        {% endif %}
        {% if storewide_sale %}{% include "product/sale_details.html" %}{% endif %}

            <tr><td></td><td><input type="submit" value="{% trans "Continue Checkout" %}"/></td></tr>
        </table>
        </form>
    </div>
</div>
{% endblock %}